### PR TITLE
Include optimize-css-assets-webpack-plugin for dist build.

### LINKED ISSUE #123: Optimize CSS output for dist builds
**Enhancement** 

We currently do not apply any CSS optimization to our build output so we have some duplicated classes (due to css-module composition) and unused variable blocks as well as whitespace and non-shorthand style definitions.
Adding the `optimize-css-assets-webpack-plugin` webpack plugin for dist builds will achieve this for us.

**Example code**
``` typescript
...includeWhen(!args.watch && !args.withTests, (args) => {
   return [new OptimizeCssAssetsPlugin()( options )];
}),
```

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)

**Description:**
Adds `OptimizeCssAssetsPlugin` for dist mode.

Resolves #123

### CODE REVIEW

**Comment by tomdye** [comment]
This currently removes the CSS sourcemaps as well. Do we want these for our built CSS?

**Comment by mwistrand** [comment]
This build is failing to due to a breaking change in one of webpack's modules used by `CoreLoadPlugin`. There is a fix included in #122, but the build failure is unrelated to any functionality included in this PR.

**Comment by tomdye** [comment]
@mwistrand im just going to have a quick look to see if i can turn sourcemaps on, this `cssProcessorOptions: { sourcemap: true }` should do it.

**Comment by mwistrand** [comment]
@tomdye Am I correct that `cssnano` does not provide an option for external source maps? So far I only see inline source map support, which, as you pointed out, adds a lot of weight to the built CSS file.

**Pull request merged**
